### ISSUE TITLE
TypeError: plot_mosaic_helper() got an unexpected keyword argument 'labels'

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#334]
This bug has been introduced in #330 

cc @jbwexler 
```
Traceback (most recent call last):
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/mriqc-0.9.0rc1-py2.7.egg/mriqc/interfaces/viz.py", line 186, in _run_interface
    labels=labels)
TypeError: plot_mosaic_helper() got an unexpected keyword argument 'labels'
Interface PlotSpikes failed to run.
```

**Comment by oesteban** [comment]
cc @jokedurnez

**Comment by mfalkiewicz** [comment]
Hello, just wanted to confirm that I get exactly the same error with the latest dev branch.
